name: Quality Checks

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint_and_format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier (check)
        run: npx prettier --check "**/*.{js,jsx,ts,tsx,css,md,yml,yaml}"

      - name: Format with Prettier (if needed)
        if: failure()
        run: |
          npx prettier --write "**/*.{js,jsx,ts,tsx,css,md,yml,yaml}"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore(format): aplicar formato Prettier" || echo "No hay cambios que commitear"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
